### PR TITLE
don't hardcode hover menu widths

### PR DESCRIPTION
**Pull request by kareila**
CODE TOUR: I noticed that there were hardcoded widths in the dropdown hover menus (18em in Tropo and 14em in Gradation Horizontal). Letting them adjust to the width of the text looks better, in my opinion.

Before:
Screenshot 2023-07-08 at 4 19 59 PM

After:
Screenshot 2023-07-08 at 4 20 44 PM

### CODE REVIEW

**Comment by momijizukamori** [comment]
Hmmm. I think I'd like to see maybe 1rem of padding or margin (whichever works best with the existing CSS) added to the right-hand side of the list items - the longest item looks a touch cramped to me. But overall I agree!

**Comment by kareila** [comment]
I think I like 0.5rem?

No padding:
Screenshot 2023-07-13 at 8 55 51 PM

1rem:
Screenshot 2023-07-13 at 8 56 34 PM

0.5rem:
Screenshot 2023-07-13 at 8 57 05 PM

**Comment by kareila** [comment]
I don't think Gradation needs any additional padding.

Screenshot 2023-07-13 at 9 01 00 PM

**Comment by momijizukamori** [comment]
Yeah, I'm fine with the 0.5rem! And agree, Gradation seems fine.

**Comment by zorkian** [comment]
can confirm this is CSS

images look good!

**Pull request merged**
